### ISSUE TITLE
[Feature suggestion] Fork this for Raycast

### ISSUE THREAD

**Issue by kylemitchell** [ericwbailey/alfred-wcag-workflow#1]
### Feature suggestion

I'd love to have this feature but I don't use Alfred. Can a Raycast user get some love? 

### Have you referenced the "Features I would like help with" portion of the README?

- [ ] I have

### Who would you like to work on this feature?

- [ ] I would like to work on this feature
- [ ] I would like the repo owner (@ericwbailey) to work on this feature

**Comment by ericwbailey** [comment]
I'd love to help, but I'm borderline burnt out and [just do not have the time and energy to create and maintain](https://github.com/ericwbailey/alfred-wcag-workflow#can-you-make-a-raycast-extension) a Raycast version of this. 

If it's helpful for you, I can definitely drop a gist of the JSON I made to make this all work for your own efforts.
